#!/bin/bash
set -e

echo "[+] Comenzando hardenizado de control de acceso y auditoría en Debian 12..."

# Ensure Uncomplicated Firewall is installed.
sudo apt install -y ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 2222/tcp
# Ensure ufw service is enabled.
sudo ufw --force enable
	
# Ensure iptables-persistent is not installed.
sudo apt purge iptables-persistent

# Ensure rsyslog is installed.
sudo apt install -y rsyslog 
# Ensure rsyslog Service is enabled.
sudo systemctl --now enable rsyslog

# Ensure permissions on /etc/ssh/sshd_config are configured.
sudo chown root:root /etc/ssh/sshd_config
sudo chmod og-rwx /etc/ssh/sshd_config
# Change SSH Port to :2222.
sudo sed -i 's/^#Port 22/Port 2222/' /etc/ssh/sshd_config
sudo sed -i 's/^Port[ \t]\+22$/Port 2222/' /etc/ssh/sshd_config
# Ensure SSH X11 forwarding is disabled.
sudo sed -i 's/^X11Forwarding yes/X11Forwarding no/' /etc/ssh/sshd_config
# Ensure SSH MaxAuthTries is set to 4 or less.
sudo sed -i 's/^#MaxAuthTries 6/MaxAuthTries 4/' /etc/ssh/sshd_config
sudo sed -i 's/^MaxAuthTries 6/MaxAuthTries 4/' /etc/ssh/sshd_config
# Ensure SSH root login is disabled.
sudo sed -i 's/^#PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config
sudo sed -i 's/^PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config
# Ensure SSH access is limited.
#sudo echo "AllowUsers user" >> /etc/ssh/sshd_config
# Ensure SSH warning banner is configured.
sudo sed -i 's|^#*Banner .*|Banner /etc/issue.net|' /etc/ssh/sshd_config
sudo grep -q "^Banner /etc/issue.net" /etc/ssh/sshd_config || echo "Banner /etc/issue.net" >> /etc/ssh/sshd_config
# Ensure SSH AllowTcpForwarding is disabled.
sudo sed -i 's/^#AllowTcpForwarding yes/AllowTcpForwarding no/' /etc/ssh/sshd_config
sudo sed -i 's/^AllowTcpForwarding yes/AllowTcpForwarding no/' /etc/ssh/sshd_config
# Ensure SSH MaxStartups is configured.
sudo sed -i 's/^#MaxStartups 10:30:100/maxstartups 9:29:99/' /etc/ssh/sshd_config
sudo sed -i 's/^MaxStartups 10:30:100/maxstartups 9:29:99/' /etc/ssh/sshd_config

# Aplica contraseña obligatoria para ingresar
sudo sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
sudo grep -q '^AuthenticationMethods' /etc/ssh/sshd_config || echo 'AuthenticationMethods publickey,password' | sudo tee -a /etc/ssh/sshd_config > /dev/null

sudo systemctl restart ssh
sudo systemctl restart sshd

echo "[✔] Controles de acceso realizados correctamente..."
