#!/bin/bash

set -e

# Ensure auditd is installed.
sudo apt install -y auditd audispd-plugins 
# Ensure auditd service is enabled.
sudo systemctl --now enable auditd

# Ensure auditing for processes that start prior to auditd is enabled
sudo sed -i 's/^GRUB_CMDLINE_LINUX="/GRUB_CMDLINE_LINUX="audit=1 /' /etc/default/grub
sudo update-grub

# Ensure audit_backlog_limit is sufficient
sudo sed -i 's/^GRUB_CMDLINE_LINUX="/GRUB_CMDLINE_LINUX="audit_backlog_limit=8192 /' /etc/default/grub
sudo update-grub

#  Ensure audit log storage size is configured
sudo sed -i 's/^\s*max_log_file\s*=.*/max_log_file = 32/' /etc/audit/auditd.conf

# Ensure audit logs are not automatically deleted
sudo sed -i 's/^\s*max_log_file_action\s*=.*/max_log_file_action = keep_logs/' /etc/audit/auditd.conf

# Ensure sudo log file exists.
echo 'Defaults logfile="/var/log/sudo.log"' > /etc/sudoers.d/log_sudo
chmod 440 /etc/sudoers.d/log_sudo
touch /var/log/sudo.log
chmod 600 /var/log/sudo.log
chown root:root /var/log/sudo.log