#!/bin/bash
set -e

apt-mark hold openssh-server
sudo apt update -y
sudo apt upgrade -y

sudo wget https://github.com/Velocidex/velociraptor/releases/download/v0.74/velociraptor-v0.74.3-linux-amd64
sudo chmod +x velociraptor-v0.74.3-linux-amd64
sudo mv velociraptor-v0.74.3-linux-amd64 /usr/local/bin/velociraptor

sudo velociraptor config generate > server.config.yaml
sudo sed -i 's/^\( *bind_address: \)127\.0\.0\.1/\10.0.0.0/' server.config.yaml

sudo velociraptor --config server.config.yaml user add --role=administrator admin Velocirraptor2025


sudo tee /etc/systemd/system/velociraptor.service > /dev/null <<EOL
[Unit]
Description=Velociraptor linux amd64
After=syslog.target network.target

[Service]
Type=simple
Restart=always
RestartSec=120
LimitNOFILE=20000
Environment=LANG=en_US.UTF-8
ExecStart=/usr/local/bin/velociraptor -c /server.config.yaml gui -v

[Install]
WantedBy=multi-user.target
EOL

sudo systemctl daemon-reload
sudo systemctl enable --now velociraptor


###########################################################

sudo velociraptor --config /server.config.yaml config client > /home/admin/client.config.yaml

sudo sed -i 's|https://localhost:8000/|https://10.100.13.15:8000/|' /home/admin/client.config.yaml


cat > /home/admin/.ssh/id_ed25519 << 'EOF'
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACC1YX/wjFoGxSekubJ7nCg3lbDNe6v+F3MXrk8u9VmY2gAAAJibuibMm7om
zAAAAAtzc2gtZWQyNTUxOQAAACC1YX/wjFoGxSekubJ7nCg3lbDNe6v+F3MXrk8u9VmY2g
AAAEDOS/3CpQG/X5CMXjpmBdXaYJdFnq8USeblIfA+LZSSQ7Vhf/CMWgbFJ6S5snucKDeV
sM17q/4XcxeuTy71WZjaAAAAFWFkbWluQGlwLTEwLTEwMC0xMy0xNQ==
-----END OPENSSH PRIVATE KEY-----
EOF

chmod 600 /home/admin/.ssh/id_ed25519

#scp -P 2222 -o StrictHostKeyChecking=no /home/admin/client.config.yaml admin@10.100.13.10:/home/admin/

