#!/bin/bash
set -e

apt-mark hold openssh-server
sudo apt update -y
sudo apt upgrade -y

sudo wget https://github.com/Velocidex/velociraptor/releases/download/v0.74/velociraptor-v0.74.3-linux-amd64
sudo chmod +x velociraptor-v0.74.3-linux-amd64
sudo mv velociraptor-v0.74.3-linux-amd64 /usr/local/bin/velociraptor

sudo velociraptor config generate > server.config.yaml
sudo sed -i 's/^\( *bind_address: \)127\.0\.0\.1/\10.0.0.0/' server.config.yaml

sudo velociraptor --config server.config.yaml user add --role=administrator admin Velocirraptor2025


sudo tee /etc/systemd/system/velociraptor.service > /dev/null <<EOL
[Unit]
Description=Velociraptor linux amd64
After=syslog.target network.target

[Service]
Type=simple
Restart=always
RestartSec=120
LimitNOFILE=20000
Environment=LANG=en_US.UTF-8
ExecStart=/usr/local/bin/velociraptor -c /server.config.yaml gui -v

[Install]
WantedBy=multi-user.target
EOL

sudo systemctl daemon-reload
sudo systemctl enable --now velociraptor


###########################################################

sudo velociraptor --config /server.config.yaml config client > client.config.yaml

sudo sed -i 's|https://localhost:8000/|https://10.100.13.15:8000/|' /client.config.yaml


cat > /home/admin/.ssh/id_ed25519 << 'EOF'
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACBkcYsru5kBQCu/s0+DzEcm/XeF/B4P+CwkPFrB8w3/LgAAAJghCIpcIQiK
XAAAAAtzc2gtZWQyNTUxOQAAACBkcYsru5kBQCu/s0+DzEcm/XeF/B4P+CwkPFrB8w3/Lg
AAAECuVTX2LFOWUVWPRRRHMazWaMrFQVO1bLz2zerCNHTwFmRxiyu7mQFAK7+zT4PMRyb9
d4X8Hg/4LCQ8WsHzDf8uAAAAFWFkbWluQGlwLTEwLTEwMC0xMy0xNQ==
----END OPENSSH PRIVATE KEY-----
EOF

chmod 600 /home/admin/.ssh/id_ed25519
