#!/bin/bash
set -e

#sudo wget https://github.com/Velocidex/velociraptor/releases/download/v0.74/velociraptor-v0.74.3-linux-amd64
#sudo chmod +x velociraptor-v0.74.3-linux-amd64
#sudo mv velociraptor-v0.74.3-linux-amd64 /usr/local/bin/velociraptor


tee -a /home/admin/.ssh/authorized_keys << 'EOF'
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILVhf/CMWgbFJ6S5snucKDeVsM17q/4XcxeuTy71WZja admin@ip-10-100-13-15
EOF

sudo chown -R admin:admin /home/admin/.ssh
sudo chmod 700 /home/admin/.ssh
sudo chmod 600 /home/admin/.ssh/authorized_keys
