#!/bin/bash
set -e

apt-mark hold openssh-server
sudo apt update -y
sudo apt upgrade -y
sudo apt install sshpass -y

sudo wget https://github.com/Velocidex/velociraptor/releases/download/v0.74/velociraptor-v0.74.3-linux-amd64
sudo chmod +x velociraptor-v0.74.3-linux-amd64
sudo mv velociraptor-v0.74.3-linux-amd64 /usr/local/bin/velociraptor

sudo velociraptor config generate > server.config.yaml
sudo sed -i 's/^\( *bind_address: \)127\.0\.0\.1/\10.0.0.0/' server.config.yaml

sudo velociraptor --config server.config.yaml user add --role=administrator admin Velocirraptor2025


sudo tee /etc/systemd/system/velociraptor.service > /dev/null <<EOL
[Unit]
Description=Velociraptor linux amd64
After=syslog.target network.target

[Service]
Type=simple
Restart=always
RestartSec=120
LimitNOFILE=20000
Environment=LANG=en_US.UTF-8
ExecStart=/usr/local/bin/velociraptor -c /server.config.yaml gui -v

[Install]
WantedBy=multi-user.target
EOL

sudo systemctl daemon-reload
sudo systemctl enable --now velociraptor


###########################################################

sudo velociraptor --config /server.config.yaml config client > /home/admin/client.config.yaml

sudo sed -i 's|https://localhost:8000/|https://10.100.13.15:8000/|' /home/admin/client.config.yaml


sudo tee /home/admin/.ssh/id_ed25519 << 'EOF'
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACCMfc8LmbWsoKaE4DdPmP6yoXTawv+BuDCkOxVGd9SjxAAAAJgMibjfDIm4
3wAAAAtzc2gtZWQyNTUxOQAAACCMfc8LmbWsoKaE4DdPmP6yoXTawv+BuDCkOxVGd9SjxA
AAAED3+/SY9ZK+NwdeyJJGSM43glrA0TMIUU1W8euTobG7jIx9zwuZtaygpoTgN0+Y/rKh
dNrC/4G4MKQ7FUZ31KPEAAAAFWFkbWluQGlwLTEwLTEwMC0xMy0xNQ==
-----END OPENSSH PRIVATE KEY-----
EOF

sudo chmod 600 /home/admin/.ssh/id_ed25519
sudo chown admin:admin /home/admin/.ssh/id_ed25519

#sshpass -p 'ContrasenaProvisoria.ORT25' scp -P 2222 -o StrictHostKeyChecking=no /home/admin/client.config.yaml admin@10.100.13.10:/home/admin/
